apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: petclinic
  namespace: flux-system
spec:
  chart:
    spec:
      chart: petclinic
      version: "0.1.0-8e22eb4"
      sourceRef:
        kind: HelmRepository
        name: ckcluster
        namespace: flux-system
  values:
    replicaCount: 2