apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: petclinic
  namespace: flux-system
spec:
  values:
    replicaCount: 10
    image:
      repository: ckcluster.azurecr.io/petclinic
      tag: 0f3de8c3e43802b01df1d34bd390bd93479073c2
  chart:
    spec:
      version: 0.1.0-0f3de8c
