apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: shared
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  path: ./shared/sources
  sourceRef:
    kind: GitRepository
    name: platform-config
