apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/npi/base/apps/hello-world
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-npi
