# kyverno-helmrepo.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h
  url: https://kyverno.github.io/kyverno/
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
# kyverno-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
  annotations:
    # one-off: forces Helm to reattempt an install/upgrade if it got stuck
    helm.toolkit.fluxcd.io/force: "true"  
spec:
  interval: 10m
  targetNamespace: kyverno
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      # Pin a version if you want strict reproducibility (recommended).
      # version: 3.1.0
  install:
    createNamespace: true     # <- create kyverno ns if it doesn't exist
    crds: Create                 # ensure CRDs are installed on first install
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace          # keep CRDs up to date on upgrades
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    admissionController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["get","list","watch","create","update","patch", "delete"]
    backgroundController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["get","list","watch","create","update","patch", "delete"]  
  # Create the target n
