name: Bump hello-world image (dev)

on:
  workflow_dispatch:
    inputs:
      new_tag:
        description: "New image tag for hello-world (e.g., v1.2.4-dev)"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      FILE: clusters/npi/overlays/dev/apps/hello-world/kustomization.yaml
      IMAGE_NAME: ghcr.io/acme/hello-world   # <-- adjust if yours differs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Update image tag in overlay
        env:
          NEW_TAG: ${{ inputs.new_tag }}
        run: |
          # Robustly set/insert the image tag entry
          yq -i '
            if has("images") then
              if (.images[]? | select(.name == env(IMAGE_NAME))) then
                (.images[] |= (select(.name == env(IMAGE_NAME)) * {"newTag": env(NEW_TAG)}))
              else
                .images += [{"name": env(IMAGE_NAME), "newTag": env(NEW_TAG)}]
              end
            else
              .images = [{"name": env(IMAGE_NAME), "newTag": env(NEW_TAG)}]
            end
          ' "$FILE"

          echo "Changed file:"
          git --no-pager diff -- "$FILE"

      # Optional: quick validation that the overlay still builds
      # - name: Validate kustomize build (dev overlay)
      #   run: |
      #     sudo snap install kustomize --classic || true
      #     kustomize build clusters/npi/overlays/dev >/dev/null

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(dev): bump hello-world to ${{ inputs.new_tag }}"
          title: "chore(dev): bump hello-world to ${{ inputs.new_tag }}"
          body: |
            Bumps the **hello-world** image in the **dev** overlay.

            - Path: `clusters/npi/overlays/dev/apps/hello-world/kustomization.yaml`
            - Image: `${{ env.IMAGE_NAME }}`
            - New tag: `${{ inputs.new_tag }}`
          branch: "chore/bump-hello-world-dev-${{ inputs.new_tag }}"
          labels: "auto-pr, dev, hello-world"
          add-paths: |
            ${{ env.FILE }}
          signoff: true
